name: pymrio
channels: 
  - defaults
  - anaconda
  - conda-forge
  - konstantinstadler
dependencies: 
  - pandas >= 1.0
  - numpy >= 1.20
  - matplotlib >= 2.0.0
  - requests >= 2.18
  - xlrd > 1.1.0 
  - openpyxl >= 3.0.6
  - docutils >= 0.14
  - pip
  - pip:
    - pymrio

