name: pymrio
channels: 
  - defaults
  - anaconda
  - conda-forge
  - konstantinstadler
dependencies: 
  - pandas >= 1.0
  - numpy >= 1.13.4
  - matplotlib >= 2.0.0
  - requests >= 2.18
  - xlrd >= 1.1.0 
  - openpyxl
  - docutils >= 0.14
  - pip
  - pip:
    - pymrio

