name: pymrio_dev
channels: 
  - conda-forge
  - anaconda
  - defaults
dependencies: 
  # core
  - python >= 3.9
  - pandas >= 1.5
  - pyarrow >= 11
  - requests >= 2.18
  - xlrd > 1.1.0 
  - openpyxl
  # - openpyxl >= 3.0.6, < 3.1.1
  - docutils >= 0.14
  - matplotlib
  # testing and developing
  - pdbpp
  - country_converter >= 0.8.0
  - pytest >= 5.4.3
  - isort >= 5.6.0
  - nbval
  - black >= 22.8
  - ipython
  - jupyterlab=3.*
  - jupytext
  - coveralls
  - pynvim
  - sphinx >= 1.6.4
  - sphinx_rtd_theme >= 0.2.4
  - ipykernel
  - nbsphinx
  - more-itertools
  - faker
